language: python
python:
  - "2.7"
env:
  global:
    - TORNPSQL_USERNAME=postgres
    - TORNPSQL_HOST=127.0.0.1
    - TORNPSQL_DATABASE=tornpsql
services: postgres
before_script:
  - psql -c 'create database tornpsql;' -U postgres
  - psql tornpsql -c 'create extension hstore' -U postgres
script:
  - python -m unittest discover -s tests
