language: python
python:
  - "2.7"
notifications:
  email: false
env:
  global:
    - TORNPSQL_USERNAME=postgres
    - TORNPSQL_HOST=127.0.0.1
    - TORNPSQL_DATABASE=tornpsql
services: postgres
before_script:
  - python setup.py install
  - pip install coveralls
  - psql -c 'create database tornpsql;' -U postgres
  - psql tornpsql -c 'create extension hstore' -U postgres
script:
  - coverage run -m unittest discover -s tests
after_success:
  - coveralls
